### ISSUE TITLE
Button does not function

### ISSUE THREAD

**Issue by maycie-morris** [gravyhtx/shopify_product-tear-sheet#1]
I have added all code to the necessary files but when clicking the button I receive the error:
1564:2932 Uncaught TypeError: Cannot read properties of null (reading 'innerHTML')
    at printDiv (1564:2932:61)
    at HTMLInputElement.onclick (1564:2874:117)

**Comment by gravyhtx** [comment]
Thanks for notifying me on this! We went over the previous code and updated everything to where the repo is at now on Sept 15, 2022. The issue happened because I was previously using an ID to get the innerHTML of the description div which may not appear on every project so I changed it to be universal using {{ product.description }} instead.

There are a few more changes in the repo that I added today, but I believe you and I knocked it out to get your project going at least. I am just documenting that we resolved the issue here in case anyone else has used the repo with issues.

I appreciate you reaching out and glad we're getting this repo updated so it can be useful to as many people as possible!

_Note: We discussed the ability to change the product to the proper variant when a user selects a different variant. I may put this into another version since that's an important function for some people. Currently the product information gets set into Local Storage as soon as the page loads, so either we will want to update the necessary product info every time the user changes product variants or when `tearSheet()` gets called._
